apiVersion: v1
kind: Service
metadata:
  name: telecon
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort:   # Port exposed to the outside
  selector:
    app: telecon-8956fbfd9
  type: NodePort
